# Generated by Django 5.2.7 on 2025-10-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL de l'image du produit", null=True, verbose_name="URL de l'image"),
        ),
    ]
